version: "3"
services:

  pushpin:
    build:
      context: .
      dockerfile: pushpin.Dockerfile
    ports:
      - "7999:7999"
      - "5561:5561"
      - "5562:5562"
    depends_on:
      - go-service

  go-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"