version: "3"
services:

  pushpin:
    build:
      context: .
      dockerfile: pushpin.Dockerfile
    ports:
      - "7999:7999"
      - "5561:5561"
      - "5562:5562"
    depends_on:
      - go-service
    network_mode: "host"

  zero-server:
    build:
      context: .
      dockerfile: python.Dockerfile
    network_mode: "host"

  zero-client:
    build:
      context: .
      dockerfile: python.Dockerfile
    network_mode: "host"
  
  go-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5562:5562"
    network_mode: "host"  