version: "3"
services:

  pushpin:
    image: fanout/pushpin:latest
    network_mode: "host"
    volumes:
      - ./routes:/etc/pushpin/routes
    ports:
      - "7999:7999"
      - "5561:5561"
      - "5562:5562"
    environment:
      PKG_CONFIG_PATH: "/usr/local/Cellar/zeromq/4.3.4/lib/pkgconfig/"